### ISSUE TITLE
Occasional Crash in dns

### ISSUE THREAD

**Issue by Jeevhi** [libevent/libevent#1130]
Occasional crash when using evdns_getaddrinfo with callback (asynchronous). It generally happens when another async evdns_getaddrinfo() invoked  for the same host even before the first request was over. 

In our case, we noticed this only for the multiple requests for the same host  but it maybe happening with different hosts too.

Below is the crash report. libevent version 2.1.12 stable. 

```
Core was generated by `/simba/bin/simba'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa633010ca7 in __sanitizer::SignalContext::GetAddress() const () from /lib64/libasan.so.5
[Current thread is 1 (Thread 0x7fa62d3ba700 (LWP 1174))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.28-42.el8.1.x86_64 libasan-8.2.1-3.5.el8.x86_64 libgcc-8.2.1-3.5.el8.x86_64 libstdc++-8.2.1-3.5.el8.x86_64 mysql-libs-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 openssl-libs-1.1.1-8.el8.x86_64
(gdb) bt
#0  0x00007fa633010ca7 in __sanitizer::SignalContext::GetAddress() const () from /lib64/libasan.so.5
#1  0x00007fa632ff8329 in __asan::AsanOnDeadlySignal(int, void*, void*) () from /lib64/libasan.so.5
#2  0x000000000044d5f6 in signal_oldhandler (signo=signo@entry=11) at signal.cpp:96
#3  0x0000000000438c54 in on_signal (signo=11) at main.cpp:602
#4  <signal handler called>
#5  0x00000000005170e8 in min_heap_erase_ (e=0x6120007afdc0, s=0x617000103548) at minheap-internal.h:100
#6  event_queue_remove_timeout (base=base@entry=0x617000103400, ev=ev@entry=0x6120007afdc0) at event.c:3284
#7  0x0000000000518b6b in event_del_nolock_ (ev=ev@entry=0x6120007afdc0, blocking=blocking@entry=2) at event.c:2851
#8  0x0000000000518d12 in event_del_ (ev=0x6120007afdc0, blocking=2) at event.c:2780
#9  0x000000000052835c in free_getaddrinfo_request (data=0x6120007afd40) at evdns.c:4372
#10 0x000000000052d1ba in evdns_getaddrinfo_gotresolve (result=<optimized out>, type=<optimized out>, count=<optimized out>, 
    ttl=<optimized out>, addresses=<optimized out>, arg=<optimized out>) at evdns.c:4638
#11 0x0000000000526dbd in reply_run_callback (d=0x61600034b380, user_pointer=<optimized out>) at evdns.c:820
#12 0x000000000051b5da in event_process_active_single_queue (base=base@entry=0x617000103400, activeq=0x60200008cc50, 
    max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1697
#13 0x000000000051c067 in event_process_active (base=0x617000103400) at event.c:1783
#14 event_base_loop (base=0x617000103400, flags=flags@entry=0) at event.c:2006
#15 0x000000000051c2a7 in event_base_dispatch (event_base=<optimized out>) at event.c:1817
#16 0x000000000046e742 in async_run (data=0x60200008cc30) at asyncsock.cpp:916
#17 0x00007fa632cea2de in start_thread () from /lib64/libpthread.so.0
#18 0x00007fa6308caa63 in clone () from /lib64/libc.so.6

```

**Comment by azat** [comment]
Thanks for the report, will take a look.

In the mean time can you run under TSAN? And/or provide reproducer?
Also one more question, have you enabled pthread support (using `evthread_use_pthreads()`)?

**Comment by Jeevhi** [comment]
We are not calling `evthread_use_pthreads()`. However, there is only one event base and the loop is running from a single thread. Does `evthread_use_pthreads()` requires in this case?

Below is the code `async_context_new()` is the one time initialization. 

```
void *async_context_new(const char *name) {
        async_context_t *c = (async_context_t *)calloc(1, sizeof(async_context_t));

        struct event_config *cfg = event_config_new();
        event_config_require_features(cfg, EV_FEATURE_EARLY_CLOSE);
        c->base = event_base_new_with_config(cfg);
        event_config_free(cfg);

        c->dnsbase = evdns_base_new(c->base, 1);

        // wrapper around pthread_create
        create_thread(async_run, c, 0, name);
        return c;
}

static void *async_run(void *data) {
        async_context_t *c = (async_context_t *) data;
        while(1) {
                int rv = event_base_dispatch(c->base);

                //handle error condition
        }
        return NULL;
}
```

**Comment by azat** [comment]
>We are not calling evthread_use_pthreads(). However, there is only one event base and the loop is running from a single thread. Does evthread_use_pthreads() requires in this case?

If the loop is running from a single thread, but access to events (or some other API) from multiple threads, then you should enable it, however if you accessing events from the same thread as event_loop then you don't

**Comment by azat** [comment]
Can you please run under TSAN? And/or provide reproducer? Also do you hit it everytime, IOW  does it reliably reproduced?

**Comment by Jeevhi** [comment]
I will add evthread_use_pthreads() and see if that helps. what would be the right place to add it?  Should be after event_base_new() or before? 

Regarding the occurrence, it's occasional and happens in high load. I am a bit cautious putting TSAN in the production code

Also do you have any comments on performance penalty due to `evthread_use_pthreads()`, will be helpful.

**Comment by azat** [comment]
>I will add evthread_use_pthreads() and see if that helps. what would be the right place to add it? Should be after event_base_new() or before?

Before any of `event_*` `ev*` calls

>Regarding the occurrence, it's occasional and happens in high load. I am a bit cautious putting TSAN in the production code

But you are ok in running under ASAN in production? (noticed `__asan::AsanOnDeadlySignal` in your stacktrace)

>Also do you have any comments on performance penalty due to evthread_use_pthreads(), will be helpful.

This will add required synchronizations, so regular mutex overhead, but it should not be significant especially if you don't have lock contention (if we are talking about futexes)

**Comment by Jeevhi** [comment]
We are calling `evthread_use_pthreads()` now. It took long to reproduce but it did, the exact same crash even with `evthread_use_pthreads()`. 

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004eea58 in min_heap_erase_ (e=0x7ff234012700, s=0x7ff248014448) at minheap-internal.h:100
100	minheap-internal.h: No such file or directory.
[Current thread is 1 (Thread 0x7ff29837b700 (LWP 22099))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.28-42.el8.1.x86_64 libgcc-8.2.1-3.5.el8.x86_64 libstdc++-8.2.1-3.5.el8.x86_64 mysql-libs-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 openssl-libs-1.1.1-8.el8.x86_64
(gdb) bt
#0  0x00000000004eea58 in min_heap_erase_ (e=0x7ff234012700, s=0x7ff248014448) at minheap-internal.h:100
#1  event_queue_remove_timeout (base=base@entry=0x7ff248014300, ev=ev@entry=0x7ff234012700) at event.c:3284
#2  0x00000000004f04db in event_del_nolock_ (ev=ev@entry=0x7ff234012700, blocking=blocking@entry=2) at event.c:2851
#3  0x00000000004f0682 in event_del_ (ev=0x7ff234012700, blocking=2) at event.c:2780
#4  0x00000000004ffccc in free_getaddrinfo_request (data=0x7ff234012680) at evdns.c:4372
#5  0x0000000000504b2a in evdns_getaddrinfo_gotresolve (result=<optimized out>, type=<optimized out>, count=<optimized out>, 
    ttl=<optimized out>, addresses=<optimized out>, arg=<optimized out>) at evdns.c:4638
#6  0x00000000004fe72d in reply_run_callback (d=0x7ff23c034490, user_pointer=<optimized out>) at evdns.c:820
#7  0x00000000004f2f4a in event_process_active_single_queue (base=base@entry=0x7ff248014300, activeq=0x7ff248013940, 
    max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1697
#8  0x00000000004f39d7 in event_process_active (base=0x7ff248014300) at event.c:1783
#9  event_base_loop (base=0x7ff248014300, flags=flags@entry=0) at event.c:2006
#10 0x00000000004f3c17 in event_base_dispatch (event_base=<optimized out>) at event.c:1817
#11 0x0000000000445de4 in async_run (data=0x7ff2480138c0) at asyncsock.cpp:921
#12 0x00007ff29b1e32de in start_thread () from /lib64/libpthread.so.0
#13 0x00007ff298dc3a63 in clone () from /lib64/libc.so.6

```

**Comment by azat** [comment]
Can you also enable libevent debug mode? (`event_enable_debug_mode()`)
It can catch some API misuse (although I doubt that this will give more details, since this is not triggered via direct `event_*` usage)
BTW any chance on a reproducer for this? (i.e. some docker image if it requires specific versions)

**Comment by Jeevhi** [comment]
I will enable event_enable_debug_mode  and let you know. 

Can you elaborate on `reproducer` and I will see if I can get you whatever you need. It takes really long to reproduce, this time it took over 10 days after the last restart. 

About the environment, I am running it on CentOS 8. Now I have enabled gcc stack protector (earlier was using ASAN) to see if we can get more info.

**Comment by azat** [comment]
>Can you elaborate on reproducer and I will see if I can get you whatever you need

Minimized (if it is possilbe) sample that I can compile/run and reproduce the problem

**Comment by Jeevhi** [comment]
Azat, I am now able reproduce more frequently launching 32 threads and each calling evdns_getaddrinfo 

Run below program multiple times and sooner or later it will crash

```
#include <event2/dns.h>
#include <event2/util.h>
#include <event2/event.h>

#include <sys/socket.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <pthread.h>

int n_pending_requests = 0;
struct event_base *base = NULL;

struct user_data {
    char *name; /* the name we're resolving */
    int idx; /* its position on the command line */
};

void callback(int errcode, struct evutil_addrinfo *addr, void *ptr)
{
   
    struct user_data *data = ptr;
    const char *name = data->name;
    if (errcode) {
        printf("callback: %d. %s -> %s\n", data->idx, name, evutil_gai_strerror(errcode));
    } else {
        struct evutil_addrinfo *ai;
        printf("%d. %s", data->idx, name);
        if (addr->ai_canonname)
            printf("callback: [%s]", addr->ai_canonname);
        puts("");
        for (ai = addr; ai; ai = ai->ai_next) {
            char buf[128];
            const char *s = NULL;
            if (ai->ai_family == AF_INET) {
                struct sockaddr_in *sin = (struct sockaddr_in *)ai->ai_addr;
                s = evutil_inet_ntop(AF_INET, &sin->sin_addr, buf, 128);
            } else if (ai->ai_family == AF_INET6) {
                struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)ai->ai_addr;
                s = evutil_inet_ntop(AF_INET6, &sin6->sin6_addr, buf, 128);
            }
            if (s)
                printf("callback:    -> %s\n", s);
        }
        evutil_freeaddrinfo(addr);
    }
    free(data->name);
    free(data);
    if (--n_pending_requests == 0)
        event_base_loopexit(base, NULL);
}

void *dns_request(void *base) {
        struct evutil_addrinfo hints;
        struct evdns_getaddrinfo_request *req;
        struct user_data *user_data;
    	struct evdns_base *dnsbase = (struct evdns_base *)base;
        memset(&hints, 0, sizeof(hints));
        hints.ai_family = AF_UNSPEC;
        hints.ai_flags = EVUTIL_AI_CANONNAME;
        /* Unless we specify a socktype, we'll get at least two entries for
         * each address: one for TCP and one for UDP. That's not what we
         * want. */
        hints.ai_socktype = SOCK_STREAM;
        hints.ai_protocol = IPPROTO_TCP;

        if (!(user_data = malloc(sizeof(struct user_data)))) {
            perror("malloc");
            exit(1);
        }

	user_data->name = strdup("something");

        req = evdns_getaddrinfo(dnsbase, "google.com", NULL /* no service name given */,
                          &hints, callback, user_data);
        if (req == NULL) {
          printf("    [request returned immediately]\n");
          /* No need to free user_data or decrement n_pending_requests; that
           * happened in the callback. */
        }
}

int create_thread(struct evdns_base *dnsbase) {
        size_t stacksize = 0x4f000;

        pthread_attr_t attr;
        pthread_attr_init(&attr);
        pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
        pthread_attr_setstacksize(&attr, stacksize);
	pthread_t t;
        pthread_create(&t, &attr, dns_request, dnsbase);
        return 0;
}


/* Take a list of domain names from the command line and resolve them in
 * parallel. */
int main(int argc, char **argv)
{
    int i;
    struct evdns_base *dnsbase;

    if (argc == 1) {
        puts("No addresses given.");
        return 0;
    }
    base = event_base_new();
    if (!base)
        return 1;
    dnsbase = evdns_base_new(base, 1);
    if (!dnsbase)
        return 2;

    evthread_use_pthreads();
    for (i = 1; i < 32; ++i) {
	    create_thread(dnsbase);
    }

      event_base_dispatch(base);

    evdns_base_free(dnsbase, 0);
    event_base_free(base);

    return 0;
}

```

```
Below is the crash from above program

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./a.out aaaa'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000406e8d in min_heap_shift_up_ (s=0x7a7428, e=0x7f4e6c001670, hole_index=17) at minheap-internal.h:168
168	    while (hole_index && min_heap_elem_greater(s->p[parent], e))
[Current thread is 1 (Thread 0x7f4e78a2c700 (LWP 9436))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-101.el8.x86_64
(gdb) bt
#0  0x0000000000406e8d in min_heap_shift_up_ (s=0x7a7428, e=0x7f4e6c001670, hole_index=17) at minheap-internal.h:168
#1  min_heap_push_ (e=0x7f4e6c001670, s=0x7a7428) at minheap-internal.h:75
#2  event_queue_insert_timeout (ev=0x7f4e6c001670, base=0x7a72e0) at event.c:3434
#3  event_add_nolock_ (ev=ev@entry=0x7f4e6c001670, tv=tv@entry=0x7a7788, tv_is_absolute=tv_is_absolute@entry=0) at event.c:2734
#4  0x00000000004083a6 in event_add (ev=ev@entry=0x7f4e6c001670, tv=0x7a7788) at event.c:2495
#5  0x0000000000413789 in evdns_request_transmit (req=req@entry=0x7f4e6c001630) at evdns.c:2293
#6  0x0000000000413901 in request_submit (req=req@entry=0x7f4e6c001630) at evdns.c:2870
#7  0x0000000000414d2a in search_request_new (base=base@entry=0x7a7750, handle=handle@entry=0x7f4e6c0014e0, type=type@entry=28, 
    name=name@entry=0x419944 "google.com", flags=flags@entry=0, 
    user_callback=user_callback@entry=0x417b20 <evdns_getaddrinfo_gotresolve>, user_arg=0x7f4e6c001290) at evdns.c:3279
#8  0x000000000041856e in evdns_base_resolve_ipv6 (base=base@entry=0x7a7750, name=name@entry=0x419944 "google.com", 
    flags=flags@entry=0, callback=callback@entry=0x417b20 <evdns_getaddrinfo_gotresolve>, ptr=ptr@entry=0x7f4e6c001290) at evdns.c:2969
#9  0x00000000004189fa in evdns_getaddrinfo (dns_base=0x7a7750, nodename=0x419944 "google.com", servname=<optimized out>, 
    hints_in=<optimized out>, cb=0x402496 <callback>, arg=<optimized out>) at evdns.c:4808
#10 0x0000000000402727 in dns_request () at evdns.c:1306
#11 0x00007f4e78e992de in start_thread () from /lib64/libpthread.so.0
#12 0x00007f4e78bcae83 in clone () from /lib64/libc.so.6

```

**Comment by Jeevhi** [comment]
@azat were you able to reproduce? Let me know if you need more info.

**Comment by azat** [comment]
@Jeevhi sorry for the delay (lots of work)

I've looked at the example, and using it I can reproduce the failure, however `evthread_use_pthreads` should be placed before any libevent calls (https://github.com/libevent/libevent/issues/1130#issuecomment-762024932), in particular before `event_base_new` (since at that time the locks are created, and since you did not enable pthreads support they were not initialized and locks are no-op)

**Comment by azat** [comment]
Also here is how you can see the race by yourself:

```sh
clang -fsanitize=thread -g3 -pthread -levent_core -levent_pthreads -levent_extra dns.c -o dns
./dns foobar.com
```

```
WARNING: ThreadSanitizer: data race (pid=7257)                                                                                           
  Read of size 1 at 0x7b4800010165 by main thread:                                                                                       
    #0 memcpy <null> (dns+0x8f6f7)                                  
    #1 name_parse /src/le/libevent/.cmake-debug/../evdns.c:1241:3 (libevent_extra-2.2.so.1+0x15fc7)                                      
    #2 __libc_start_main <null> (libc.so.6+0x27b24)                                                                                      
                                                                    
  Previous write of size 8 at 0x7b4800010160 by thread T1:         
    #0 malloc <null> (dns+0x5395d)                                  
    #1 event_mm_malloc_ /src/le/libevent/.cmake-debug/../event.c:3533:10 (libevent_core-2.2.so.1+0x23a1d)                                
                                                                    
  Location is heap block of size 328 at 0x7b4800010080 allocated by thread T1:                                                           
    #0 malloc <null> (dns+0x5395d)                                 
    #1 event_mm_malloc_ /src/le/libevent/.cmake-debug/../event.c:3533:10 (libevent_core-2.2.so.1+0x23a1d)                                
                                                                    
  Thread T1 (tid=7259, finished) created by main thread at:
    #0 pthread_create <null> (dns+0x8c55e)                                                                                               
    #1 create_thread /src/le/tmp/issue-1130/dns.c:95:9 (dns+0xd1da0)                                                                     
    #2 main /src/le/tmp/issue-1130/dns.c:124:9 (dns+0xd1ec7)        
                                                                                                                                         
SUMMARY: ThreadSanitizer: data race (/src/le/tmp/issue-1130/dns+0x8f6f7) in memcpy                                                       
....
```

**Comment by Jeevhi** [comment]
@azat thanks, I will move evthread_use_pthreads and try this out. However, I have two questions.

1) why only evdns_getaddrinfo causes crash and not other libevent apis, even when evthread_use_pthreads was not used. We have been using Bufferevents  from multiple threads, without using evthread_use_pthreads and never encountered crash in libevent. It started crashing only after we started using evdns_getaddrinfo 

2) While waiting for your reply, we replaced evdns_getaddrinfo with getaddrinfo and then everything is stable again. That again points to the above observation. In addition to that, we have now also observed that evdns_getaddrinfo is slower compared to getaddrinfo. On CentOS 8, the getaddrinfo is at least 20% faster compared to evdns_getaddrinfo. This is conclusion is from approx 10,000 getaddrinfo calls. 

Can you shed some lights on it please

**Comment by azat** [comment]
>why only evdns_getaddrinfo causes crash and not other libevent apis, even when evthread_use_pthreads was not used. We have been using Bufferevents from multiple threads, without using evthread_use_pthreads and never encountered crash in libevent. It started crashing only after we started using evdns_getaddrinfo

I guess bufferevents are not conflicts with each other, but actually they should fail too if you access them from multiple threads (you can try compile with TSAN and check)

> While waiting for your reply, we replaced evdns_getaddrinfo with getaddrinfo and then everything is stable again.

Sure, since this is just a glibc call.

> That again points to the above observation. In addition to that, we have now also observed that evdns_getaddrinfo is slower compared to getaddrinfo. On CentOS 8, the getaddrinfo is at least 20% faster compared to evdns_getaddrinfo. This is conclusion is from approx 10,000 getaddrinfo calls.

Interesting, actually evdns_getaddrinfo is async, and scheduling request by request is not it's pattern, it should be used in case when you need to resolve lots of addresses, you schedule them and then poll.
