### ISSUE TITLE
evdns.c:2161: Assertion conn->state == TS_CONNECTED failed in tcp_read_message

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#1401]
```
evdns.c:2161: Assertion conn->state == TS_CONNECTED failed in tcp_read_message
```

stack:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f73f5168148 in __GI_abort () at abort.c:79
#2  0x000000000045d39f in event_exit ()
#3  0x000000000045d992 in event_errx ()
#4  0x000000000046bea6 in tcp_read_message ()
#5  0x000000000046db55 in client_tcp_read_packet_cb ()
#6  0x000000000044022e in bufferevent_run_readcb_ ()
#7  0x00000000004473a1 in bufferevent_trigger_nolock_ ()
#8  0x0000000000446d6b in bufferevent_readcb ()
#9  0x000000000045275e in event_persist_closure ()
#10 0x0000000000451d88 in event_process_active_single_queue ()
#11 0x000000000044cd4a in event_process_active ()
#12 0x000000000044bc8e in event_base_loop ()
#13 0x000000000044b837 in event_base_dispatch ()
```

I'm on 21e2862689edc59b6265998c4a1a2729552ab0b1 more or less.

**Comment by azat** [comment]
Hi @ghazel,

There is not a lot of details in the provided stacktrace.
Are you sure that the problem is not in your code? Have you tried to run it under TSAN/ASAN?
Is the problem reproducible?

Likely #1004 is related,  @seleznevae maybe you have a guess?

**Comment by ghazel** [comment]
Pretty sure it’s not a problem in my code — I don’t use DNS over TCP explicitly.

**Comment by Hackerl** [comment]
I seem to have the same problem：
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3fe2468716 in bufferevent_get_input (bufev=0x0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/bufferevent.c:426
426             return bufev->input;
[Current thread is 1 (LWP 267882)]
(gdb) bt
#0  0x00007f3fe2468716 in bufferevent_get_input (bufev=0x0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/bufferevent.c:426
#1  0x00007f3fe2451796 in tcp_read_message (conn=0x7f3fe1b735f0, msg=0x7ffd7e204558, msg_len=0x7ffd7e204554) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/evdns.c:2126
#2  0x00007f3fe2453d49 in client_tcp_read_packet_cb (bev=0x7f3fe1e9f000, ctx=0x7f3fe28530a0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/evdns.c:2848
#3  0x00007f3fe2468097 in bufferevent_run_readcb_ (bufev=0x7f3fe1e9f000, options=0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/bufferevent.c:251
#4  0x00007f3fe246d22a in bufferevent_trigger_nolock_ (bufev=0x7f3fe1e9f000, iotype=2, options=0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/bufferevent-internal.h:418
#5  0x00007f3fe246d5af in bufferevent_readcb (fd=126, event=2, arg=0x7f3fe1e9f000) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/bufferevent_sock.c:214
#6  0x00007f3fe24728dc in event_persist_closure (base=0x7f3fe2866ac0, ev=0x7f3fe1e9f010) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/event.c:1659
#7  0x00007f3fe2472bd4 in event_process_active_single_queue (base=0x7f3fe2866ac0, activeq=0x7f3fe2833c90, max_to_process=2147483647, endtime=0x0)
    at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/event.c:1718
#8  0x00007f3fe2473186 in event_process_active (base=0x7f3fe2866ac0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/event.c:1819
#9  0x00007f3fe2473abc in event_base_loop (base=0x7f3fe2866ac0, flags=0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/event.c:2068
#10 0x00007f3fe247320e in event_base_dispatch (event_base=0x7f3fe2866ac0) at /opt/vcpkg/buildtrees/libevent/src/757b64d6d1-bfa17b9727.clean/event.c:1853
```
