### ISSUE TITLE
Memory leak detected for simple hello world example

### ISSUE THREAD

**Issue by ljhm** [libevent/libevent#1412]
I write this hello world example based on libevent/sample/hello-world.c. 
In this example, I want the server to write a hello to two clients, and 
two clients to write a hello to server. And read and write calls are not 
nested together, so any of them can write a hello without read first.

I currently encountered these problems:

1. Memory usage increasing observed for both server and clients in top command
2. Memory leaks detected by Address Sanitizer

I write an equivalent hello world in boost asio. The server and clients
only consume about 12M memory each. The memory usage is stable and low, 
and no leaks detected there.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                    
   1922 ljh       20   0   20.0t 653.7m   3.2m R  33.0  16.8   4:08.32 ./build/main/server 9995                   
   1993 ljh       20   0   20.0t 366.3m   3.3m R  48.5   9.4   0:53.08 ./build/main/client 192.168.1.4 9995 bbb   
   1925 ljh       20   0   20.0t 369.6m   3.2m R  49.2   9.5   4:34.40 ./build/main/client 192.168.1.4 9995 aaa  
```   

When press Ctrl + C on terminal to kill server, address sanitizer reports memory leaks.

```
==1922==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 219449344 byte(s) in 58492 object(s) allocated from:
    #0 0x7ff9cfd0fe8f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7ff9cfc395bb in evbuffer_expand_fast_.part.0 (/home/ljh/Downloads/libevent/build/lib/libevent_core-2.2.so.1+0xc5bb)

Indirect leak of 2048 byte(s) in 2 object(s) allocated from:
    #0 0x7ff9cfd0fe8f in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7ff9cfc39253 in evbuffer_add (/home/ljh/Downloads/libevent/build/lib/libevent_core-2.2.so.1+0xc253)

Indirect leak of 1040 byte(s) in 2 object(s) allocated from:
    #0 0x7ff9cfd10037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7ff9cfc46a72 in bufferevent_socket_new (/home/ljh/Downloads/libevent/build/lib/libevent_core-2.2.so.1+0x19a72)

Indirect leak of 576 byte(s) in 4 object(s) allocated from:
    #0 0x7ff9cfd10037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7ff9cfc36572 in evbuffer_new (/home/ljh/Downloads/libevent/build/lib/libevent_core-2.2.so.1+0x9572)

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x7ff9cfd10037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7ff9cfc407e1 in evbuffer_add_cb (/home/ljh/Downloads/libevent/build/lib/libevent_core-2.2.so.1+0x137e1)

SUMMARY: AddressSanitizer: 219453088 byte(s) leaked in 58502 allocation(s).
```

---

```
//server.cpp

// ./libevent/sample/hello-world.c
/*
  This example program provides a trivial server program that listens for TCP
  connections on port 9995.  When they arrive, it writes a short message to
  each client connection, and closes each connection once it is flushed.

  Where possible, it exits cleanly in response to a SIGINT (ctrl-c).
*/


#include <string.h>
#include <string>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#ifndef _WIN32
#include <netinet/in.h>
# ifdef _XOPEN_SOURCE_EXTENDED
#  include <arpa/inet.h>
# endif
#include <sys/socket.h>
#endif

#include <unistd.h>
#include <arpa/inet.h>
#include <stdlib.h>

#include <event2/bufferevent.h>
#include <event2/buffer.h>
#include <event2/listener.h>
#include <event2/util.h>
#include <event2/event.h>

#include <sanitizer/lsan_interface.h>

static const char MESSAGE[] = "Hello, World! ";

static int PORT = 9995;

static void listener_cb(struct evconnlistener *, evutil_socket_t,
    struct sockaddr *, int socklen, void *);
static void conn_readcb(struct bufferevent *, void *);
static void conn_writecb(struct bufferevent *, void *);
static void conn_eventcb(struct bufferevent *, short, void *);
static void signal_cb(evutil_socket_t, short, void *);

void handlerCont(int signum){
    printf("SIGCONT %d\n", signum);
#ifndef NDEBUG
  __lsan_do_recoverable_leak_check();
#endif
}

int
main(int argc, char **argv)
{
    struct event_base *base;
    struct evconnlistener *listener;
    struct event *signal_event;

    struct sockaddr_in sin = {0};
#ifdef _WIN32
    WSADATA wsa_data;
    WSAStartup(0x0201, &wsa_data);
#endif

    signal(SIGPIPE, SIG_IGN);
    signal(SIGCONT, handlerCont); // $ man 7 signal

    base = event_base_new();
    if (!base) {
        fprintf(stderr, "Could not initialize libevent!\n");
        return 1;
    }

    printf("Usage: server [port]\n");
    if (argc == 2) {
        PORT = atoi(argv[1]);
    }

    sin.sin_family = AF_INET;
    sin.sin_port = htons(PORT);
    sin.sin_addr.s_addr = htons(INADDR_ANY);

    listener = evconnlistener_new_bind(base, listener_cb, (void *)base,
        LEV_OPT_REUSEABLE|LEV_OPT_CLOSE_ON_FREE, -1,
        (struct sockaddr*)&sin, sizeof(sin));

    if (!listener) {
        fprintf(stderr, "Could not create a listener!\n");
        return 1;
    }

    printf("Listen on port: %d\n", PORT);

    signal_event = evsignal_new(base, SIGINT, signal_cb, (void *)base);

    if (!signal_event || event_add(signal_event, NULL)<0) {
        fprintf(stderr, "Could not create/add a signal event!\n");
        return 1;
    }

    event_base_dispatch(base);

    evconnlistener_free(listener);
    event_free(signal_event);
    event_base_free(base);

    printf("Done\n");
    return 0;
}

static void
listener_cb(struct evconnlistener *listener, evutil_socket_t fd,
    struct sockaddr *sa, int socklen, void *user_data)
{
    struct sockaddr_in *in = (struct sockaddr_in *)sa;
    printf("Accept connection: %s:%u \n",
        inet_ntoa(in->sin_addr), in->sin_port);

    struct event_base *base = (event_base *)user_data;
    struct bufferevent *bev;

    bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE);
    if (!bev) {
        fprintf(stderr, "Error constructing bufferevent!\n");
        event_base_loopbreak(base);
        return;
    }
    bufferevent_setcb(bev, conn_readcb, conn_writecb, conn_eventcb, NULL);
    bufferevent_enable(bev, EV_WRITE | EV_READ);

    // bufferevent_write(bev, MESSAGE, strlen(MESSAGE)); //
}

static void
conn_readcb(struct bufferevent *bev, void *user_data)
{
    char buf[1024] = {'\0'};
    struct evbuffer *input = bufferevent_get_input(bev);
    size_t length = evbuffer_get_length(input);

    if (length > 0) {
        bufferevent_read(bev, buf, sizeof(buf) - 1);
        printf("%s", buf);
    }
}

static void
conn_writecb(struct bufferevent *bev, void *user_data)
{
    // struct evbuffer *output = bufferevent_get_output(bev);
    // size_t length = evbuffer_get_length(output);
    // if (length == 0) {
    //     printf("flushed answer\n");
    //     // bufferevent_free(bev);
    // }

    // sleep(1); //test
    static int cnt = 1;
    char buf[1000] = {'\0'};
    snprintf(buf, sizeof(buf),"hello from server %d\n", cnt++);
    bufferevent_write(bev, buf, strlen(buf));
}

static void
conn_eventcb(struct bufferevent *bev, short events, void *user_data)
{
    int finished = 0;

    if (events & BEV_EVENT_EOF) {
        printf("Connection closed.\n");
        finished = 1;
    } else if (events & BEV_EVENT_ERROR) {
        printf("Got an error on the connection: %s\n",
            strerror(errno));/*XXX win32*/
        finished = 1;
    }
    /* None of the other events can happen here, since we haven't enabled
     * timeouts */

    if (finished) {
        free(user_data); // ?
        bufferevent_free(bev);
    }
}

static void
signal_cb(evutil_socket_t sig, short events, void *user_data)
{
    struct event_base *base = (event_base *)user_data;
    struct timeval delay = { 2, 0 };

    printf("Caught an interrupt signal; exiting cleanly in two seconds.\n");

    event_base_loopexit(base, &delay);
}
```

---

```
// client.cpp

// ./libevent/sample/hello-world.c
/*
  This example program provides a trivial server program that listens for TCP
  connections on port 9995.  When they arrive, it writes a short message to
  each client connection, and closes each connection once it is flushed.

  Where possible, it exits cleanly in response to a SIGINT (ctrl-c).
*/


#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#ifndef _WIN32
#include <netinet/in.h>
# ifdef _XOPEN_SOURCE_EXTENDED
#  include <arpa/inet.h>
# endif
#include <sys/socket.h>
#endif

#include <unistd.h>
#include <arpa/inet.h>
#include <stdlib.h>

#include <event2/bufferevent.h>
#include <event2/buffer.h>
#include <event2/listener.h>
#include <event2/util.h>
#include <event2/event.h>

#include <sanitizer/lsan_interface.h>

static const char MESSAGE[] = "Hello, World! ";
const char *message2;

static int PORT = 9995;

// static void listener_cb(struct evconnlistener *, evutil_socket_t,
//     struct sockaddr *, int socklen, void *);
static void conn_readcb(struct bufferevent *, void *);
static void conn_writecb(struct bufferevent *, void *);
static void conn_eventcb(struct bufferevent *, short, void *);
static void signal_cb(evutil_socket_t, short, void *);

void handlerCont(int signum){
    printf("SIGCONT %d\n", signum);
#ifndef NDEBUG
  __lsan_do_recoverable_leak_check();
#endif
}

int
main(int argc, char **argv)
{
    struct event_base *base;
    // struct evconnlistener *listener;
    struct event *signal_event;

    struct sockaddr_in sin = {0};
#ifdef _WIN32
    WSADATA wsa_data;
    WSAStartup(0x0201, &wsa_data);
#endif

    if (argc != 4) {
        printf("Usage: client <ip> <port> <msg>\n");
        return 1;
    }

    signal(SIGPIPE, SIG_IGN);
    signal(SIGCONT, handlerCont); // $ man 7 signal

    base = event_base_new();
    if (!base) {
        fprintf(stderr, "Could not initialize libevent!\n");
        return 1;
    }

    const char *host = argv[1];
    const int port = atoi(argv[2]);
    message2 = argv[3];

    sin.sin_family = AF_INET;
    sin.sin_port = htons(port);
    inet_aton(host, (struct in_addr*)&sin.sin_addr.s_addr);

    // listener = evconnlistener_new_bind(base, listener_cb, (void *)base,
    //     LEV_OPT_REUSEABLE|LEV_OPT_CLOSE_ON_FREE, -1,
    //     (struct sockaddr*)&sin,
    //     sizeof(sin));

    // if (!listener) {
    //     fprintf(stderr, "Could not create a listener!\n");
    //     return 1;
    // }

    struct bufferevent *    bev = bufferevent_socket_new(base, -1, BEV_OPT_CLOSE_ON_FREE);
    if (!bev) {
        fprintf(stderr, "Error constructing bufferevent!\n");
        event_base_loopbreak(base);
        return 1;
    }

    bufferevent_setcb(bev, conn_readcb, conn_writecb, conn_eventcb, NULL);

    if (bufferevent_socket_connect(
        bev, (struct sockaddr *)&sin, sizeof(sin)) < 0)
    {
        bufferevent_free(bev);
        printf("Error setting up connection!\n");
        return 1;
    }

    bufferevent_enable(bev, EV_WRITE | EV_READ);

    // signal_event = evsignal_new(base, SIGINT, signal_cb, (void *)base);

    // if (!signal_event || event_add(signal_event, NULL)<0) {
    //     fprintf(stderr, "Could not create/add a signal event!\n");
    //     return 1;
    // }

    event_base_dispatch(base);

    // evconnlistener_free(listener);
    // event_free(signal_event);
    event_base_free(base);

    printf("Done\n");
    return 0;
}

// static void
// listener_cb(struct evconnlistener *listener, evutil_socket_t fd,
//     struct sockaddr *sa, int socklen, void *user_data)
// {
//     struct sockaddr_in *in = (struct sockaddr_in *)sa;
//     printf("accept connection: %s:%u \n",
//         inet_ntoa(in->sin_addr), in->sin_port);

//     struct event_base *base = (event_base *)user_data;
//     struct bufferevent *bev;

//     bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE);
//     if (!bev) {
//         fprintf(stderr, "Error constructing bufferevent!\n");
//         event_base_loopbreak(base);
//         return;
//     }
//     bufferevent_setcb(bev, conn_readcb, conn_writecb, conn_eventcb, NULL);
//     bufferevent_enable(bev, EV_WRITE | EV_READ);
// }

static void
conn_readcb(struct bufferevent *bev, void *user_data)
{
    char buf[1024] = {'\0'};
    struct evbuffer *input = bufferevent_get_input(bev);
    size_t length = evbuffer_get_length(input);

    if (length > 0) {
        bufferevent_read(bev, buf, sizeof(buf) - 1);
        printf("%s", buf);
    }
}

static void
conn_writecb(struct bufferevent *bev, void *user_data)
{
    // struct evbuffer *output = bufferevent_get_output(bev);
    // size_t length = evbuffer_get_length(output);
    // if (length == 0) {
    //     printf("flushed answer\n");
    //     // bufferevent_free(bev);
    // }

    // sleep(1); //test
    static int cnt = 1;
    char buf[1000] = {'\0'};
    snprintf(buf, sizeof(buf),"hello from client %s %d\n", message2, cnt++);
    bufferevent_write(bev, buf, strlen(buf));
}

static void
conn_eventcb(struct bufferevent *bev, short events, void *user_data)
{
    int finished = 0;

    if (events & BEV_EVENT_EOF) {
        printf("Connection closed.\n");
        finished = 1;
    } else if (events & BEV_EVENT_ERROR) {
        printf("Got an error on the connection: %s\n",
            strerror(errno));/*XXX win32*/
        finished = 1;
    } else if (events & BEV_EVENT_CONNECTED) {
        // ./libevent/ChangeLog-2.0
        // Changes in 2.0.3-alpha (20 Nov 2009):
        // When we send a BEV_EVENT_CONNECTED to indicate connected
        // status, we no longer invoke the write callback as well unless
        // we actually wrote data too.

        // ./libevent/sample/ssl-client-mbedtls.c
        const char *buf = "Client connected.\n";
        bufferevent_write(bev, buf, strlen(buf));

        //or, call write callback directly
        // ./libevent/test/test-ratelim.c
        // conn_writecb(bev, user_data); //
    }

    /* None of the other events can happen here, since we haven't enabled
     * timeouts */

    if (finished) {
        struct timeval delay = { 2, 0 };
        free(user_data);
        bufferevent_free(bev);
        event_base_loopexit((event_base *)user_data, &delay);
    }
}

// static void
// signal_cb(evutil_socket_t sig, short events, void *user_data)
// {
//     struct event_base *base = (event_base *)user_data;
//     struct timeval delay = { 2, 0 };

//     printf("Caught an interrupt signal; exiting cleanly in two seconds.\n");

//     event_base_loopexit(base, &delay);
// }

```

**Comment by ljhm** [comment]
Hi @azat, thank you very much for the help again.
