### ISSUE TITLE
bufferever_openssl threading deadlock

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#200]
Looks like the event_base is waiting on the bev lock, but the thread holds the bev lock and is waiitng on the current_event_cond.

(yes, the bufferevent is marked as `BEV_OPT_THREADSAFE`, and I called `evthread_use_pthreads()`, and I setup OpenSSL with `CRYPTO_set_locking_callback` and friends)

```C
Thread 3 (Thread 0x7f5abe67b700 (LWP 3678)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000048793b in evthread_posix_cond_wait (_cond=0x1686db0, _lock=0x1683e60, tv=0x0) at evthread_pthread.c:156
#2  0x00000000004630aa in event_del_internal (ev=0x2791ce8) at event.c:2263
#3  0x0000000000462f40 in event_del (ev=0x2791ce8) at event.c:2231
#4  0x0000000000488ee2 in consider_writing (bev_ssl=0x2791c50) at bufferevent_openssl.c:881
#5  0x000000000048976a in be_openssl_outbuf_cb (buf=0x2791f30, cbinfo=0x7f5abe67acf0, arg=0x2791c50) at bufferevent_openssl.c:1119
#6  0x0000000000466c29 in evbuffer_run_callbacks (buffer=0x2791f30, running_deferred=0) at buffer.c:486
#7  0x0000000000466d1c in evbuffer_invoke_callbacks (buffer=0x2791f30) at buffer.c:508
#8  0x0000000000469d80 in evbuffer_add (buf=0x2791f30, data_in=0x286bbf0, datlen=276) at buffer.c:1612
#9  0x000000000046d9f4 in bufferevent_write (bufev=0x2791c50, data=0x286bbf0, size=276) at bufferevent.c:379
#10 0x000000000040c912 in threaded_sender (arg=0x286bbd0) at myapp.c:1521
#11 0x000000000041d376 in worker (arg=0x0) at threadpool.c:47
#12 0x00007f5ac801bf18 in start_thread (arg=0x7f5abe67b700) at pthread_create.c:308
#13 0x00007f5ac6986b9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

Thread 1 (Thread 0x7f5ac89a6800 (LWP 3672)):
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f5ac801dddc in _L_lock_865 () from /lib64/libpthread.so.0
#2  0x00007f5ac801dcf9 in __GI___pthread_mutex_lock (mutex=0x2792000) at pthread_mutex_lock.c:85
#3  0x0000000000487739 in evthread_posix_lock (mode=0, _lock=0x2792000) at evthread_pthread.c:73
#4  0x000000000046e1d5 in _bufferevent_incref_and_lock (bufev=0x2791c50) at bufferevent.c:582
#5  0x0000000000489088 in be_openssl_writeeventcb (fd=31, what=4, ptr=0x2791c50) at bufferevent_openssl.c:947
#6  0x00000000004605e0 in event_persist_closure (base=0x1686b20, ev=0x2791ce8) at event.c:1319
#7  0x00000000004606e9 in event_process_active_single_queue (base=0x1686b20, activeq=0x1683e40) at event.c:1363
#8  0x00000000004609a2 in event_process_active (base=0x1686b20) at event.c:1438
#9  0x000000000046103a in event_base_loop (base=0x1686b20, flags=0) at event.c:1655
#10 0x0000000000460a3f in event_base_dispatch (event_base=0x1686b20) at event.c:1468
#11 0x0000000000411474 in main () at myapp.c:2756
```

**Comment by ghazel** [comment]
It seems this is a very old issue with 2.0.x, addressed in 2.1
