### ISSUE TITLE
"Segmentation fault" when writing data with bufferevent_write()

### ISSUE THREAD

**Issue by bitkevin** [libevent/libevent#380]
I write a simple long time connection tcp server with bufferevent. Sometimes it's crach when writing data:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  evbuffer_chain_insert (buf=buf@entry=0x1da28d0, chain=chain@entry=0x7f04ec006540) at buffer.c:303
303                     while ((*ch) && ((*ch)->off != 0 || CHAIN_PINNED(*ch)))
(gdb) bt
#0  evbuffer_chain_insert (buf=buf@entry=0x1da28d0, chain=chain@entry=0x7f04ec006540) at buffer.c:303
#1  0x00007f0505c60177 in evbuffer_add (buf=0x1da28d0, data_in=0x7f04ec063948, datlen=201) at buffer.c:1625
#2  0x00007f0505c62bc0 in bufferevent_write (bufev=<optimized out>, data=<optimized out>, size=<optimized out>) at bufferevent.c:379

...

(gdb) p *ch
$1 = (struct evbuffer_chain *) 0x736148746267222c
(gdb) p (*ch)->off
Cannot access memory at address 0x7361487462672244
```

I havn't use write_callback function, just call bufferevent_write() to write data, should I use write_callback function wait for a write event than call bufferevent_write()?

```
bufferevent_setcb(bev,
                    Server::readCallback,
                    NULL,  /* we use bufferevent, so don't need to watch write events */
                    Server::eventCallback, (void*)conn);
  bufferevent_enable(bev, EV_READ);
```

libevent version: `libevent-2.0.22-stable`

**Comment by azat** [comment]
Hi Kevin,

Which version of libevent do you use?
Can you try latest from git?
Can you produce a reproducer?
Can you run under valgrind (maybe there was some memory corruption before)?

Thanks,
Azat.

**Comment by azat** [comment]
@bitkevin closing this one for now, please reopen once you will provide details.
