### ISSUE TITLE
(Bug?)Deadlock happend

### ISSUE THREAD

**Issue by lzy-lyf** [libevent/libevent#512]
Version: libevent-2.0.so.5.1.4
```
Thread1:
#0  0x0000003666a0b5bc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f05cdfc6dc5 in evthread_posix_cond_wait (_cond=0xa00240, _lock=0xa001e0, tv=0x0) at evthread_pthread.c:156
#2  0x00007f05ce1d967d in event_del_internal (ev=0xc98c0ae10) at event.c:2180
#3  event_del (ev=0xc98c0ae10) at event.c:2148
#4  0x00007f05ce1e2b8a in be_socket_destruct (bufev=0xc98c0ae00) at bufferevent_sock.c:585
#5  0x00007f05ce1e181a in _bufferevent_decref_and_unlock (bufev=0xc98c0ae00) at bufferevent.c:622
#6  0x00007f05ce1e1a0b in bufferevent_free (bufev=0xc98c0ae00) at bufferevent.c:681
Thread2:
#0  0x0000003666a0e264 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003666a09523 in _L_lock_892 () from /lib64/libpthread.so.0
#2  0x0000003666a09407 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f05ce1e11ac in _bufferevent_incref_and_lock (bufev=0xc98c0ae00) at bufferevent.c:582
#4  0x00007f05ce1e2852 in bufferevent_readcb (fd=14, event=2, arg=<value optimized out>) at bufferevent_sock.c:133
#5  0x00007f05ce1da76c in event_process_active_single_queue (base=0xa20000, flags=0) at event.c:1325
#6  event_process_active (base=0xa20000, flags=0) at event.c:1392
#7  event_base_loop (base=0xa20000, flags=0) at event.c:1589
```

As you see, thread 1 tried to delete an event and hold the lock at first, then thread 2 receive read event on the same connection and prevent thread 1 from deleting the event. 
Here comes the problem: thread 1 won't complete the deleting until thread 2 finishi its work(in source code, thread 1 need a condition signal to wake up), but thread 2 won't continue working until thread 1 release the lock(in source code, thread 2 need the lock holded by thread 1).
Is this a bug , feature or misuse of libevent??

**Comment by ploxiln** [comment]
sounds related to #225 / #236

**Comment by azat** [comment]
Indeed it looks like issues mentioned by @ploxiln 
Can you please verify your program with latest libevent (compiled from git, since that patches was merged only recently and there was not release since that time)?

**Comment by azat** [comment]
Closing due to inactivity
