### ISSUE TITLE
detected memory leaks

### ISSUE THREAD

**Issue by fouzhe** [libevent/libevent#726]
I used **gcc 5.4 and AddressSanitizer**(`export CFLAGS="-g -fsanitize=address" CXXFLAGS="-g -fsanitize=address" LDFLAGS="-fsanitize=address"` before `make`)  to build [libevent](https://github.com/libevent/libevent/tree/1d2ef90032bc842bc2e295ee4adce3408b6d85da), there are memory leaks when testing `test-fdleak` in the folder `test` by command `./test-fdleak`.
Here is ASAN information:
```
==17512==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 1040 byte(s) in 2 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae77f82e7 in bufferevent_socket_new /home/fouzhe/my_fuzz/libevent/bufferevent_sock.c:354:17

Indirect leak of 648 byte(s) in 1 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae77fe52c in event_mm_calloc_ /home/fouzhe/my_fuzz/libevent/event.c:3506:13
    #2 0x7f7ae77fe52c in event_base_new_with_config /home/fouzhe/my_fuzz/libevent/event.c:614
    #3 0x7f7ae7801eb3 in event_base_new /home/fouzhe/my_fuzz/libevent/event.c:524:10
    #4 0x7f7ae689482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 544 byte(s) in 4 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae77a2587 in evbuffer_new /home/fouzhe/my_fuzz/libevent/buffer.c:366:11

Indirect leak of 384 byte(s) in 1 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae78693cf in epoll_init /home/fouzhe/my_fuzz/libevent/epoll.c:169:20
    #2 0x7f7ae77ff89d in event_base_new_with_config /home/fouzhe/my_fuzz/libevent/event.c:693:18
    #3 0x7f7ae7801eb3 in event_base_new /home/fouzhe/my_fuzz/libevent/event.c:524:10
    #4 0x7f7ae689482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4dec10 in realloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:107
    #1 0x7f7ae7834ca1 in evmap_make_space /home/fouzhe/my_fuzz/libevent/evmap.c:213:18
    #2 0x7f7ae7834ca1 in evmap_io_add_ /home/fouzhe/my_fuzz/libevent/evmap.c:282

Indirect leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae785c45e in evconnlistener_new /home/fouzhe/my_fuzz/libevent/listener.c:180:8

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae77ca4da in evbuffer_add_cb /home/fouzhe/my_fuzz/libevent/buffer.c:3320:13

Indirect leak of 64 byte(s) in 4 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae7834e53 in evmap_io_add_ /home/fouzhe/my_fuzz/libevent/evmap.c:286:2

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae786931e in epoll_init /home/fouzhe/my_fuzz/libevent/epoll.c:161:18
    #2 0x7f7ae77ff89d in event_base_new_with_config /home/fouzhe/my_fuzz/libevent/event.c:693:18
    #3 0x7f7ae7801eb3 in event_base_new /home/fouzhe/my_fuzz/libevent/event.c:524:10
    #4 0x7f7ae689482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4de9c0 in calloc /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x7f7ae7803f65 in event_mm_calloc_ /home/fouzhe/my_fuzz/libevent/event.c:3506:13
    #2 0x7f7ae7803f65 in event_base_priority_init /home/fouzhe/my_fuzz/libevent/event.c:1260

SUMMARY: AddressSanitizer: 3232 byte(s) leaked in 18 allocation(s).
```

**Comment by azat** [comment]
Thanks for the report!

This binaries should be leak-free, but not as strict as the library itself.
That said that they I'm interesting in eliminating leaks there, but this test binaries do not have regular leak checks.

Are you interested in fixing this? Or you just want them goes away?
